# Generated by Django 5.1.7 on 2025-05-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_livro_autor_livro_categoria_livro_coautor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descricao',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
